### ISSUE TITLE
How to make tests green - TODO list

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/sandbox#1008]
From some time I working on prepare stable 3.0. The first step was remove dependencies which block me to use the latest sonata bundles. - #986.

Here is list what to must be done to make tests green:
- [x] https://github.com/sonata-project/ecommerce/pull/773
- [x] release ecommerce with 773 
- [ ] make this services public (BlockBundle v3)
    - [ ] `sonata.block.context_manager`, 
    - [ ] `sonata.block.renderer`  
    - [ ] `sonata.block.cache.handle` 
- [ ] fix `Sonata\PageBundle\Command\RenderBlockCommand`
- [ ] fix cache commands or disable i until support `symfony/cache`
- [ ] fix failures from `sonata-project/notification-bundle`

**Comment by wbloszyk** [comment]
We can avoid making block services public by present BC-break in PageBundle. Then services will be injected instead taking from container. We present BC-break like this in other bundles, which will also remove deprecation from `ContainerAwareCommand`.

**Comment by VincentLanglet** [comment]
> We can avoid making block services public by present BC-break in PageBundle. Then services will be injected instead taking from container. We present BC-break like this in other bundles, which will also remove deprecation from `ContainerAwareCommand`.

I'm fine with this. Do you have time to do the PR ?
